### ISSUE TITLE
Lists in country with telephone codes are not the same length

### ISSUE THREAD

**Issue by rpbeltran** [vinaygaba/Ultimate-String-Array-List#8]
There are 235 country codes, and 237 countries listed in 'Countries with telephonice codes.xml' . I was going to try to merge the lists like was suggested in the other open issue, but the lists don't line up one to one, and so I am not sure what's going on. If it is because a country does not have a code then it probably should not be in the list. People who try to loop through the lists by country to find pairs will receive index out of bounds errors if they aren't careful tight now.

**Comment by vinaygaba** [comment]
Sure I will change this. Thanks for bringing this up. I did not notice this before.

**Comment by rpbeltran** [comment]
I fixed this and issue 8 in a PR I submitted.
